### ISSUE TITLE
No `Bind` instance for `Html` data type

### ISSUE THREAD

**Issue by coot** [alexmingoia/purescript-pux#101]
The [documentation](http://www.purescript-pux.org/docs/API/Pux/Html.html)  states that one can use `do` notation to combine `Html` elements, but the `Html` data type is missing  `Bind` instance.

**Comment by charleso** [comment]
@coot Hi, I removed the `Bind` instance because it was fundamentally broken:

https://github.com/alexmingoia/purescript-pux/pull/72

I've sent a PR to update the book to reflect this:

https://github.com/alexmingoia/purescript-pux/pull/85
