### ISSUE TITLE
Docs/css.md: Cannot import value 'size' from module Pux.CSS

### ISSUE THREAD

**Issue by janaipakos** [alexmingoia/purescript-pux#104]
Including `size` with `import Pure.CSS` as per [http://www.purescript-pux.org/docs/css.html](http://www.purescript-pux.org/docs/css.html) leads to an error: `Cannot import value size from module Pux.CSS`. I don't think `size` exists in pux-css.

Should mention of the `size` property be removed from this page, or `size` be added to pux-css?

**Comment by alexmingoia** [comment]
Docs have been updated to reflex Pux 8 release. pux-css has been deprecated in favor of using purescript-css with the style element and attributes provided in Pux 8.
