### ISSUE TITLE
Unused definition warning, module Pux, fromReact.

### ISSUE THREAD

**Issue by philderbeast** [alexmingoia/purescript-pux#105]
When compiling I get this warning.

```
WARNING in [1/7 UnusedFFIImplementations]

   The following definitions in the foreign module for module Pux are unused:

     fromReact
```

**Comment by chexxor** [comment]
It's not intended to be used by PureScript code directly, so there's no FFI function for it. It's intended to be used in an FFI file to import the component. It's documented here: https://github.com/alexmingoia/purescript-pux/blob/master/docs/react-interop/using-react-components-in-pux.md

**Comment by philderbeast** [comment]
Is there a way to stop clients of this package seeing that compiler warning?

**Comment by chexxor** [comment]
Compile with psa instead of psc is one way.

**Comment by alexmingoia** [comment]
This is no longer an issue with the Pux 8 release. There's no way to avoid the warning in Pux 7.
