### ISSUE TITLE
`Array Html` instead of `Html`

### ISSUE THREAD

**Issue by athanclark** [alexmingoia/purescript-pux#109]
This seems to be more of a philosophical question - is pux intended to succeed over elm, or is it intended to mimick it enirely? If it were to be superior, I argue that `Config`'s views should be founded on `Array <<< Html` rather than `Html`:

Pros:

- One could host an app directly on a `<body>` tag, without double-parenting
- `Arrays` are a general / free monoid, allowing one to `view foo <> view bar`

Cons:

- re-integrating into a parent element would require double mapping: `map (map FooAction) (fooView fooState)`

**Comment by chexxor** [comment]
I'd like to not be limited by Elm's design. I think I wouldn't mind rewriting my app around a monoidal Pux API.

**Comment by alexmingoia** [comment]
It's not intended to mimic Elm. The latest release, Pux 8, uses [purescript-smolder](https://github.com/bodil/purescript-smolder)'s markup monad to construct HTML. This allows `do` notation for writing views, and all sorts of other functional goodness.

**Comment by athanclark** [comment]
Thank you, that's great news. I wonder if smolder could be used to embed arbitrary `ReactElement`s - if that's the case, then we could use pux to make react-native apps!! >:O

**Comment by athanclark** [comment]
Oh wait hm, it looks like smolder doesn't support that. Maybe in the next revision, pux could be designed around a generic `element :: * -> *` type or something, then use some tricky magick to make it a generic action framework for both smolder and react? Maybe next episode. Thank you again for your help!

**Comment by chexxor** [comment]
@athanclark - I haven't tried with Pux 8, but there's some support for importing React components.
http://purescript-pux.org/docs/react-interop/ (Maybe the guide hasn't been updated for Pux 8 yet? The elements don't look like smolder elements.)
https://github.com/alexmingoia/purescript-pux/blob/master/src/Pux/Renderer/React.purs
