### ISSUE TITLE
a couple of v1.0.0 issues / quirks

### ISSUE THREAD

**Issue by joelgrus** [alexmingoia/purescript-pux#11]
hey, cool that 1.0.0 is out, I discovered it by accident today. a couple of challenges:
1. with the new `Html a` type, the `!` sugar doesn't work for childless elements.  e.g. in previous versions I would have done something like 

``` purescript
img ! src "me.jpg" ! alt "me"
```

but now the types don't work out. I ended up doing

``` purescript
img [src "me.jpg", alt "me"]
```

but is there a better way?
1.  the `withChildren` method feels like it should be called `withChild`? Since it takes a single `Html a` child element? I don't know if it's just me, but I always end up needing to use an array of child elements. I see in the examples you use `ol [] $ map ..`. Is that the cleanest way?

I ended up defining

``` purescript
withChildren' :: forall a.
                 (Array (Attribute a) -> Array (Html a) -> Html a) ->
                 Array (Html a) ->
                 Html a
withChildren' f htmls = f [] htmls

infixl 4 withChildren' as ##
```

and then doing `div ## map ...` but wasn't sure if there's a simpler way.

3 I got some issues about `react` and `react-dom` not being defined, I ended up having to `npm install` them. I guess maybe that's expected? Might be nice in the docs.

Anyway, still love the framework. :)

**Comment by alexmingoia** [comment]
1. You're right. This is an oversight on my part. I think the best solution would be to change the signature for element creation to always receive children, even for childless elements.
2. Yes, `withChildren` should probably be called `withChild`.
3. They have to be either on the `window` object or `require`'able. This lib doesn't actually bundle them. I should probably make that clear.

**Comment by alexmingoia** [comment]
I also like the idea of the `##` operator.
