### ISSUE TITLE
PUX's current status

### ISSUE THREAD

**Issue by pietro909** [alexmingoia/purescript-pux#110]
Hello,
I know that a huge refactoring is ongoing but I couldn't find any roadmap.

Where is the project going? What is the timeline?

I would like to give PUX a try for a new project but I need to understand what is planned for the future @alexmingoia 

Thank you!

**Comment by alexmingoia** [comment]
Pux will be actively maintained for the forseeable future. I'm using Pux 8 in production for multiple projects.

Today I released Pux 8. You should look at the updated [guide](https://www.purescript-pux.org) and use the [starter-app](https://github.com/alexmingoia/pux-starter-app) to get started. If you run into any issues with the new release just ping me on GitHub or Twitter.

With the latest Pux 8 release, there are no planned changes to the API or architecture. The focus going forward is improving tooling and documentation, and staying up-to-date with PureScript releases and new features.
