### ISSUE TITLE
Conform to dependency's licenses

### ISSUE THREAD

**Issue by chexxor** [alexmingoia/purescript-pux#111]
Pux 8 is using purescript-smolder, which is a LGPL licensed, which means Pux needs to conform to some LGPL requirements.

https://www.gnu.org/licenses/lgpl.html

I haven't read all, but "5. Combined Libraries." seems relevant to Pux.

**Comment by alexmingoia** [comment]
Pux only links to purescript-smolder as a dependency. There's no license violation of the LGPL section 5, Pux is a "Combined Work" not a "Combined Library". Licenses can be so confusing 😕
