### ISSUE TITLE
Todomvc example doesn't work with React (instead of preact)

### ISSUE THREAD

**Issue by jmatsushita** [alexmingoia/purescript-pux#131]
Hi there,

I'm trying to reproduce issues I'm finding when trying to use react instead of preact (and will also try to reproduce the problems I encounter with preact) and I find that replacing preact with react in the `todomvc` example results in an app that compiles but doesn't work. Keyboard events in the input field are not registered (which is what I found in my app too). 

I don't know if its related but when using `spy` from `Debug.Trace` on the event it seems that the `preact` event has the `nativeEvent` key while the react version doesn't (see screenshots below).

![image](https://user-images.githubusercontent.com/356097/27586790-04e62c62-5b42-11e7-9382-23638cb71942.png)

![image](https://user-images.githubusercontent.com/356097/27586798-0eade820-5b42-11e7-8478-6a4510df41a9.png)

Any idea of what's going on?

Cheers,

Jun

**Comment by alexmingoia** [comment]
Moved to alexmingoia/pux-todomvc#2
