### ISSUE TITLE
Real world examples

### ISSUE THREAD

**Issue by TatriX** [alexmingoia/purescript-pux#137]
I'm looking for an open source projects which use `Pux`.
Where can I find one?

Thanks!

**Comment by maddie927** [comment]
Here are some examples I found searching Github (the blog one might be a little out of date):
- https://github.com/justinwoo/purescript-etch-sketch
- https://github.com/alexmingoia/pux-todomvc
- https://github.com/rayshih/pux-todomvc
- https://github.com/dariooddenino/pux-blog

And some small ones I made a while back:
- https://github.com/spicydonuts/pux-rock-paper-scissors
- https://github.com/spicydonuts/purescript-spectacle-presentation

It'd still be great to find some larger apps with real-world concerns though.

**Comment by alexmingoia** [comment]
There's a section in the Wiki you can add to: https://github.com/alexmingoia/purescript-pux/wiki#apps-made-with-pux
