### ISSUE TITLE
Plans to update for Purescript 0.12?

### ISSUE THREAD

**Issue by roryc89** [alexmingoia/purescript-pux#157]
Hello. Are there any plans to update Pux to be compatible with Purescript 0.12? Thanks!

**Comment by alexmingoia** [comment]
I'd welcome a PR to update it. My time is focused on other projects at the moment.

**Comment by roryc89** [comment]
Thanks alex. I'll have a look into it and see if I'm able.

**Comment by roryc89** [comment]
PR ready for review. https://github.com/alexmingoia/purescript-pux/pull/158

**Comment by pkamenarsky** [comment]
@alexmingoia anything left to do on the PR?

**Comment by alexmingoia** [comment]
Merged, tagged, and published. Thanks @roryc89
