### ISSUE TITLE
Component lifecycle methods

### ISSUE THREAD

**Issue by jgoux** [alexmingoia/purescript-pux#16]
Hello,

is there a way to define [component lifecycle methods](https://facebook.github.io/react/docs/component-specs.html#lifecycle-methods) when defining a `view` ?

Thanks for this awesome library ! :+1:

**Comment by alexmingoia** [comment]
What is the use case?

**Comment by alexmingoia** [comment]
As discussed in the gitter chat, some use cases not covered by Pux:
- Trigger a focus on an input element when it is rendered.
- Trigger a blur on an input element when a key is pressed.

Are there any others you can think of? The `setTimeout` use case you mentioned in the chat is covered by `purescript-aff`'s `later'` method. 

I'll think about how to implement the focus/blur functionality in a declarative way.

**Comment by alexmingoia** [comment]
The focus use-case is now solvable with the new React interop in Pux v3. Use [`react-controlled-focus`](https://www.npmjs.com/package/react-controlled-focus) with [`fromReact`](http://www.alexmingoia.com/purescript-pux/docs/react-interop/using-react-components-in-pux.html) to turn element focus into a function of state.
