### ISSUE TITLE
Move examples to branches of pux-starter-app

### ISSUE THREAD

**Issue by alexmingoia** [alexmingoia/purescript-pux#23]
It'd be easier if instead of keeping examples in the pux repository, they would instead be branches of the pux-starter-app repository. That way anyone could get an example up and running by cloning that branch and running `npm start`.

**Comment by AphonicChaos** [comment]
If "move" means deleting the examples from this directory, I would like to respectfully disagree. In fact, I don't even use the pux-starter-app, so having to clone that repository to see examples would be rather inconvenient. 

If "move" instead means to maintain examples in both places, I'd be concerned about them becoming out of sync. 

Also, I think if I were to use the pux-starter-app, I'd only expect it to include the minimum boilerplate to get started with pux, not a bunch of extra things to only be deleted immediately.

**Comment by alexmingoia** [comment]
Good points. I agree.
