### ISSUE TITLE
SVG elements and attributes

### ISSUE THREAD

**Issue by alexmingoia** [alexmingoia/purescript-pux#3]

**Comment by justinwoo** [comment]
Do you have something specific in mind? For Elm, the virtual-dom library seems to be kind of finicky, forcing you to consider the difference in html and svg nodes and their attributes. But with React, iirc, they do conversion under the hood (which gets them in trouble sometimes) which works, e.g. https://github.com/justinwoo/purescript-etch-sketch/blob/2e8a7dd1fa78c5c0631c9006f81c5aff7c9fd2e4/src/Main.purs#L91-L115

Would work on this issue entail mostly running through and making sure there are parent/leaf node and attribute helpers?

**Comment by alexmingoia** [comment]
Yes, pretty much. You're welcome to tackle this – I'm focused on some other things right now.
