### ISSUE TITLE
Initial values of signals in `inputs` are discarded

### ISSUE THREAD

**Issue by menelaos** [alexmingoia/purescript-pux#30]
Providing an array of external signals via the `inputs` field can be problematic if one uses signals that typically fire only once at the beginning.

Take e.g. the following example in which the app is supposed to read in the current window dimensions and the current route via `Signal.DOM.windowDimensions` and `Pux.Router.sampleUrl`:

``` purescript
module Main where

import Control.Alt ( (<|>) )
import Control.Apply ( (<*) )
import Control.Monad.Eff ( Eff )
import Data.Functor ( (<$) )
import Data.Generic ( class Generic, gShow )
import Data.Maybe ( fromMaybe )
import DOM ( DOM )
import Prelude ( class Show, ($), (<<<), (<>), bind, map, show )
import Pux ( fromSimple, renderToDOM, start )
import Pux.Html ( Html, div, text )
import Pux.Router ( end, lit, router, sampleUrl )
import Signal ( Signal )
import Signal.DOM ( DimensionPair, windowDimensions )
import Signal.Time ( Time, every )

-- ##############
-- ### Router ###
-- ##############

data Route = Home | Login | NotFound

derive instance genericRoute :: Generic Route

instance showRoute :: Show Route where
  show = gShow

match :: String -> Route
match url = fromMaybe NotFound $ router url $
  Home <$ end
  <|>
  Login <$ (lit "login") <* end


-- ###############
-- ### Signals ###
-- ###############

routeSignal' :: forall eff. Eff (dom :: DOM | eff) (Signal Action)
routeSignal' = ( map <<< map ) ( RouteAction <<< match ) sampleUrl

windowDimensionsSignal' :: forall eff. Eff (dom :: DOM | eff) (Signal Action)
windowDimensionsSignal' = ( map <<< map ) ResizeAction windowDimensions

timeSignal :: Signal Action
timeSignal = map TimeAction (every 2000.0)


-- #############
-- ### State ###
-- #############

type State =
  { width  :: Int
  , height :: Int
  , route  :: Route
  , time   :: Time
  }

init :: { width :: Int, height :: Int } -> String -> Time -> State
init { width, height } initialPath time =
  { width  : width
  , height : height
  , route  : match initialPath
  , time   : time
  }


-- ##############
-- ### Update ###
-- ##############

data Action
  = ResizeAction DimensionPair
  | RouteAction Route
  | TimeAction Time

update :: Action -> State -> State
update action state =
  case action of
    ResizeAction dimensions ->
      state { width = dimensions.w, height = dimensions.h }
    RouteAction newRoute ->
      state { route = newRoute }
    TimeAction newTime ->
      state { time = newTime }


-- ############
-- ### View ###
-- ############

view :: State -> Html Action
view state =
  div []
    [ div [] [ text ("Width: "  <> show state.width) ]
    , div [] [ text ("Height: " <> show state.height) ]
    , div [] [ text ("Route: "  <> show state.route) ]
    , div [] [ text ("Time: "   <> show state.time) ]
    ]


-- ############
-- ### Main ###
-- ############

main = do
  routeSignal            <- routeSignal'
  windowDimensionsSignal <- windowDimensionsSignal'

  app <- start
    { initialState : init { width : 0, height : 0 } "" 0.0
    , update       : fromSimple update
    , view         : view
    , inputs       : [ routeSignal, windowDimensionsSignal, timeSignal ]
    }

  renderToDOM "#app" app.html
```

If you run this example and visit "/login", you will notice that neither the window dimensions nor the route have been picked up.

Why is this? Looking at https://github.com/alexmingoia/purescript-pux/blob/d1e1dd51d29e74a390a3c85515ad66d62c46ae2a/src/Pux.purs#L49, the `inputs` array is reversed and the signals are merged with [`Signal.mergeMany`](https://github.com/bodil/purescript-signal/blob/68aec8d37aa4935c5fd8536ca54e772421f2822b/src/Signal.purs#L50) which calls [`Signal.merge`](https://github.com/bodil/purescript-signal/blob/68aec8d37aa4935c5fd8536ca54e772421f2822b/src/Signal.purs#L42) under the hood.

When two signals are merged, the initial value of the first signals wins. For the example above, this means that from the `inputs` array `[ routeSignal, windowDimensionsSignal, timeSignal ]` only the `TimeAction` is processed.

I don't know why `Elm` and subsequently `purescript-signal` settled on this behaviour but I think we should document some workarounds for this issue here and maybe in the documentation.

**Comment by alexmingoia** [comment]
> I don't know why Elm and subsequently purescript-signal settled on this behaviour

It's the only behavior possible. A signal only has one value at any point in time. `Signal a -> Signal a -> Signal a` can't return `Signal (List a)`, so one value must be chosen. Conceptually, a Pux app has one signal of actions and signal values/actions only "occur" discretely one-at-a-time.

If you need an initial route, window dimension, and time, then you set those in your `initialState`. There's no need for actions to control initial state. This could be documented better - I'll add it to the roadmap

**Comment by menelaos** [comment]
> It's the only behavior possible. A signal only has one value at any point
> in time. `Signal a -> Signal a -> Signal a` can't return `List a`, so one
> value must be chosen. Conceptually, a Pux app has one signal of actions
> and actions only occur discretely one-at-a-time.

Sorry, if I wasn't clear on this. I'm not suggesting for `merge` to return a `List a` as that would be impossible, like you said. Rather, I would (naively?) expect `merge` to behave similar to the [`merge`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/merge.md) from [RxJS](https://github.com/Reactive-Extensions/RxJS) which never discards a value but instead emits them one after the other.

It seems that some people in the `Elm` community have been tripped up by [this](https://github.com/evancz/start-app/issues/38) [behaviour](https://groups.google.com/forum/#!searchin/elm-discuss/fairmerge/elm-discuss/wwDSokXCiz0/RaVA8xfo5SIJ), too. 
The [`fairMerge`](http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.7.0/Signal-Extra#fairMerge) function was written to address exactly this issue, though it has not been officially endorsed (yet?).

> If you need an initial route, window dimension, and time, then you set
> those in your `initialState`. This could be documented better - I'll add
> it to the roadmap

Cool, thanks.

**Comment by jgoux** [comment]
I just had a similar issue, I needed the current route to initialize the whole app.
I passed it manually from JS to the initialState as suggested by @alexmingoia : 

``` javascript
var Main = require('../src/Main.purs');
var initialState = require('../src/Application.purs').init;
var debug = process.env.NODE_ENV === 'development'
var currentUrl = window.location.pathname + window.location.search

if (module.hot) {
    var app = Main[debug ? 'debug' : 'main'](window.puxLastState || initialState(currentUrl))();
    app.state.subscribe(function (state) {
     window.puxLastState = state;
    });
    module.hot.accept();
} else {
    Main[debug ? 'debug' : 'main'](initialState(currentUrl))();
}
```
