### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by alexmingoia** [alexmingoia/purescript-pux#34]
The [documentation](https://github.io/alexmingoia/purescript-pux) could always be better. I'd like this issue to be an open-ended discussion on the documentation.
- How can existing documentation be improved?
- What is missing from the docs?
- What is confusing about the docs?

Todo
- [ ] Add note about using `EXCEPTION` effect because Pux's `start` / `CoreEffects` is already parametized with it.

**Comment by maddie927** [comment]
I'd like to work on a "first timer to PS" page, with a section on installing PS and Atom integration and a section on PS basics like "what's are type signatures" and "basic type declarations" for people who are afraid of the Pux examples not making sense.

(This sort of section doesn't make sense for most libraries, but Pux is likely to be the first introduction to PS people coming from Elm or JS are likely to see, and I don't want to just point them to a book)

**Comment by menelaos** [comment]
I think the documentation should cover more of the cases in the [Elm architecture tutorial](https://github.com/evancz/elm-architecture-tutorial#the-elm-architecture), especially animation and multiple components with effects.

**Comment by alexmingoia** [comment]
I agree corresponding chapters for Elm architecture would be nice. You might want to check out @stratospark's translation at https://github.com/stratospark/pux-elm-architecture.

Something to keep in mind is that with the latest Elm release, all the elm-app-architecture tutorials are out-of-date. Elm is no longer passing addresses/signal channels around, and parametizes the `Html` with actions just like Pux.

**Comment by menelaos** [comment]
Do you plan on adopting the [new terminology](https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.17.md) (basically renaming `Action -> Msg` and `Effects -> Cmd`) from Elm?

**Comment by alexmingoia** [comment]
Personally, I think `Input` is a more accurate description. What does everyone think? I agree that `Action` is not the most descriptive, but `Msg` suffers the same problem. Conceptually `Action` doesn't fit with non-user input (like receiving a response from an ajax request), but neither does `Msg`. `Msg` doesn't make sense conceptually for something like clicking a button. 

`Cmd` isn't worth debating. Side-effects are a well-known terminology used throughout functional programming, and there's a huge denotational semantics around what "effects" mean. It seems incredibly confusing to use `Cmd` to denote effects. Haskell has the best and clearest terminology, using `IO` for what Elm and PureScript usually call effects. `IO` actually describes what is happening.

**Comment by kritzcreek** [comment]
I think Elm's new terminology is horrible... back to the old C days :D `Input` sounds allright but it doesn't map particularly well to things like a `requestAnimationFrame` tick and I think Action is more generic in that it doesn't imply any data arriving but rather something that provokes a ReAction.

**Comment by maddie927** [comment]
I don't see anything wrong with Action either and have started to like it a lot more in languages with types than in JS' Flux/Redux where I first started hearing it.  It's descriptive but not specific, isn't so long it needs to be abbreviated, and sort of implies "well what kind of action?", which fits well with ADTs.  So.. I'm for Actions 👍

More quirks with the Msg/Cmd names:
- Msg could be misunderstood as an alias for String
- Msg is a more common application type, like `data Action = NewMessage String`, and that doesn't read well when replacing Action with Msg
- Cmd (another abbreviation 😞) sort of hints to the Elm concept of asking the runtime to perform effects for you.  In PS there is no runtime and Eff/Aff are just special types that bend the pure-ness a little, so even if it makes sense for Elm to switch, I don't think it makes sense for PS.

(this is actually the first I've heard of Elm changing the names of these things, so I don't know if they have explained it somewhere, but it makes me think they just wanted people to stop saying "it's like Redux" 😕)

**Comment by menelaos** [comment]
@spicydonuts There are a few discussions about this in https://groups.google.com/forum/#!forum/elm-dev but there hasn't been any official announcement yet.

Personally, I prefer `Event` instead of `Action` as it fits every case from button clicks to server responses. I agree on keeping `Effects` instead of `Cmd`.

**Comment by jplatte** [comment]
There's a typo in the very first example: `type State :: Int` instead of `type State = Int`.

Also, as someone who doesn't know shit about bower, browserify, node and all that stuff, it's a bit disappointing that none of it is touched on. The guide doesn't even mention that you have to add your own `index.html`.

**Comment by alexmingoia** [comment]
@menelaos I agree with you that `Event` seems much clearer and idiomatic than `Action`.

**Comment by gabysbrain** [comment]
I'd like to see more recommendations on how to combine effects. Maybe it's my poor understanding of purescript's extensible records but I've been struggling with combining the effects from the URL router from `Pux.Router` with ajax requests.

**Comment by alexmingoia** [comment]
A section in the guide should be added about using `EXCEPTION` with Pux. See https://gitter.im/alexmingoia/purescript-pux?at=57638b68da1c26b0453711ee for conversation about it.

**Comment by maddie927** [comment]
Probably after verifying a working pattern _post_ updating to `purescript-aff` 1.0, as it changes exception behavior slightly.

**Comment by cafca** [comment]
I want to build a frontend-heavy web app and am looking at Pux as one of my options for a framework. While I like the introductory examples, what's putting me off about the documentation is the API reference. How does `data_` allow me to specify HTML data attributes? What is `forwardTo` and what does `(!)` allow me to do? It is hard to decode an explanation like `infixl 4 withAttr as !` without any comments as a beginner.

I think the API reference could be a lot more verbose.
