### ISSUE TITLE
event.preventDefault() equivalent in Pux

### ISSUE THREAD

**Issue by dboris** [alexmingoia/purescript-pux#37]
What is the equivalent to JavaScript's event.preventDefault() in Pux? My use case is a controlled textarea component which syncs with the model.

**Comment by alexmingoia** [comment]
Pux calls that for you. You can accomplish a controlled textarea like so http://www.alexmingoia.com/purescript-pux/docs/form-data.html

**Comment by dboris** [comment]
I must be doing something wrong then. I expect when typing in the textarea in the following example, the text to appear in uppercase, but it doesn't.
https://gist.github.com/dboris/9a26ca75f70226bfd353f5e29b0e2889

**Comment by menelaos** [comment]
@dboris I cannot check right now but I believe you have to use something like 

``` purescript
textarea [onInput TextChange, value state ] []
```

See https://facebook.github.io/react/docs/forms.html#why-textarea-value

**Comment by dboris** [comment]
@menelaos This solution doesn't compile -- UnknownValue error.

@alexmingoia Are the Pux html elements same as React elements?

**Comment by menelaos** [comment]
@dboris You probably forgot to import `value` from `Pux.Html.Attributes`.

**Comment by alexmingoia** [comment]
@menelaos is correct. A controlled textarea in React requires using value attribute instead of child text.

**Comment by dboris** [comment]
Yes, my mistake. The example works now. Thanks.
