### ISSUE TITLE
Alternative rendering engine

### ISSUE THREAD

**Issue by eskimor** [alexmingoia/purescript-pux#45]
[snabbdom](https://github.com/paldepind/snabbdom) was suggested to purescript-halogen. Thought I post it here too, in case you guys were not aware of it.

**Comment by alexmingoia** [comment]
A rendering engine must provide:
- Better benchmarks than React
- Declarative interface for form elements (React's controlled inputs)
- Normalized events with consistent structure (React's Synthetic event system)
- Capable of rendering HTML
- Stable and production-ready

Some possible rendering engines:
- [preact](https://github.com/developit/preact) - same API as React, but not stable yet
- [virtual-dom](https://github.com/Matt-Esch/virtual-dom) - different API, lacks controlled form input, stable?
- [snabbdom](https://github.com/paldepind/snabbdom) - different API, lacks controlled form input, stable?
- [morphdom](https://github.com/patrick-steele-idem/morphdom) - Faster and simpler than virtual DOM approaches

React already provides everything needed, so performance seems to be the only reason to replace it.

**Comment by eskimor** [comment]
Cool - nice work :-)

**Comment by coot** [comment]
Native `purescript` implementation, like [halogen-vdom](https://github.com/slamdata/purescript-halogen-vdom), has the advantage that using a haskell backend for purescript (there is one at an early stage now: [thran](https://github.com/tfausak/thran)) , one would be able to do server side rendering using a server written in haskell.

**Comment by alexmingoia** [comment]
The Pux 8 release uses the markup monad from purescript-smolder. This means you can write any virtual DOM renderer you desire. Pux 8 ships with a React renderer you can use as a reference implementation.
