### ISSUE TITLE
Make Pux.Routing a separate project

### ISSUE THREAD

**Issue by epost** [alexmingoia/purescript-pux#48]
I'm thinking it might be useful to turn `Pux.Router` into a separate project by moving the tiny bits that depend on `Pux.Html` and perhaps on `Signal` out of `Pux.Router`. Would that make sense, as an alternative to https://github.com/slamdata/purescript-routing?

**Comment by alexmingoia** [comment]
I don't think it makes sense for routing to be tied to Pux at all, not depending on `Pux.Html` or `Signal`. Ideally, a router library would provide a parser to turn URLs into routes, and a serializer to turn routes into URLs.

**Comment by cies** [comment]
When looking at server-side pre-rendering, routing becomes very important. We somehow want the same routes that are used on the client in conjunction with the history API, to work on the server to know how to pre-render an incoming request with a deep link.

Currently it says the `pux-starter-app` does server-side rendering. Well it does, technically, but it does not show how to achieve pre-rendering of deep link requests. I think that is quite a common usecase for pre-rendering (at least how I've seen it being used in React apps) that I have no idea how to achieve with pux.
