### ISSUE TITLE
is there a way to render children components into a layout component?

### ISSUE THREAD

**Issue by tdfairbrother** [alexmingoia/purescript-pux#61]
In React, you can render children components using props.children

`const Layout = props => (<div>{props.children}</div>)`

`const Menu = () => (<Layout><ul><li><a>Link</a></li></ul></Layout>)`

which would render `<ul><li><a>Link</a></li></ul>` inside the Layout div.

Is there any way to do this in Pux?

Thanks

**Comment by alexmingoia** [comment]
Yes. Views in Pux are just functions that return markup. You can pass the children to your view function in addition to the state. Just use a second argument.
