### ISSUE TITLE
How would I include raw html (eg &) into pux output?

### ISSUE THREAD

**Issue by simg** [alexmingoia/purescript-pux#69]
"&" get's turned into &amp; by the "text" function.

is there a function for rendering html without further processing ?

**Comment by maddie927** [comment]
You want the [dangerouslySetInnerHtml](https://github.com/alexmingoia/purescript-pux/blob/cde73a615eb058fdd8718b4c226e203188046c2b/src/Pux/Html/Attributes.purs#L100) prop, which is how it's done in regular React as well.

**Comment by simg** [comment]
brilliant, thank you !
