### ISSUE TITLE
Routing doesn't work in IE

### ISSUE THREAD

**Issue by akegalj** [alexmingoia/purescript-pux#76]
https://github.com/alexmingoia/purescript-pux/blob/master/src/Pux/Router.js#L37 is failing in IE. To workaround I had to use https://github.com/krambuhl/custom-event-polyfill with `window.Event = window.CustomEvent` . There is a more detailed discussion at https://github.com/krambuhl/custom-event-polyfill/pull/6#issuecomment-254439626 where maintainer of `custom-event-polyfill` claims this should be fixed in `purescript-pux`.

If you find this a valid point, we can use `CustomEvent` implementation if browser doesn't support `Event` but I am not sure this should be `pux` concern at all.

**Comment by alexmingoia** [comment]
Thanks for pointing this out! Pux 8 doesn't have this issue and your fix was published in 7.1
