### ISSUE TITLE
Call `ev.preventDefault()` for drag-and-drop events

### ISSUE THREAD

**Issue by ghost** [alexmingoia/purescript-pux#78]
Right now it seems Pux will call `preventDefault` only for `onSubmit` and `onClick` event handlers. Trying to use the drag-and-drop API, for example to handle dropped files, requires calling this function for the drag and drop events (for example, it's required to prevent the browser from navigating away from the page when an image file is dropped, most browsers will navigate to the dropped file):
- onDragStart
- onDrag
- onDragEnter
- onDragOver
- onDragEnd
- onDragLeave
- onDrop

Also, can this be made optional? Is it a good idea to force Pux users to call preventDefault, when there might be situations to run a function before allowing the default action to happen?

**Comment by alexmingoia** [comment]
Pux 8 has moved to using raw DOM event type from purescript-dom. Developers can call use preventDefault from purescript-dom when appropriate. See the updated [guide](http://purescript-pux.org/docs/events/) for more information.

With Pux 8, you can do this:

```purescript
foldp :: ∀ fx. Event -> State -> EffModel State Event (dom :: DOM | fx)
foldp (SomeAction ev) state = { state, effects: [ preventDefault ev *> pure Nothing ] }
```
