### ISSUE TITLE
canvas painting how to

### ISSUE THREAD

**Issue by Dierk** [alexmingoia/purescript-pux#86]
How would one paint onto a canvas element with the Pux approach?

**Comment by mrkgnao** [comment]
I'm interested in this too. Maybe some kind of integration with [purescript-canvas](https://github.com/purescript-contrib/purescript-canvas), pushing `Context2D` into the `EffModel`'s effect row?

**Comment by alexmingoia** [comment]
You would need to write a canvas renderer, and provide markup constructors for all the canvas elements. You can use the React renderer in Pux 8 as a reference implementation if you're interested in writing one.
