### ISSUE TITLE
Popping up modals asynchronously *inside* EffModel's effects.

### ISSUE THREAD

**Issue by PipocaQuemada** [alexmingoia/purescript-pux#87]
I'm working with an API where every API call can potentially fail with a "two-factor-authentication-code-required" error and need to be retried with the exact same arguments (modulo the two factor code).  There's also some additional stuff with using HMAC for authentication.

To make the API a bit easier to use, there's a purescript library I've already implemented. The library uses the Reader monad to take a function from the UI that runs the API call, and if the call fails it promps the user for a two-factor code and passes it to the API call: 

    type Runner a e =
     (Maybe TwoFactor -> Aff (AuthEffects e) (Either TwoFactorRequired (Either APIError (APIResponse a)))) 
      -> MaybeT (Aff a) (Either APIError (APIResponse a))

    type MyAPI e a =  forall a b. (Respondable b) =>
     ReaderT { runner :: Runner a e} (MaybeT (Aff a)) (AffjaxResponse (APIResponse b))

     getProfile :: forall e . GetProfileReq -> MyAPI (now:: NOW | e)  GetProfileResp

Is there a good way to create this callback in pux, using signals and channels?

**Comment by charleso** [comment]
@PipocaQuemada I don't think you necessarily need signals/channels for this. This is just a vague sketch of what you could possibly use. (Not tested and obviously won't compile)

```purs
main = do
  -- Create runner once
  runner <- createRunner
  start
    { update: update runner
    , ...
    }

data State =
    StateError APIError
  | StateNeedsTwoFactor GetProfileReq TwoFactorRequired
  | StateProfile GetProfileResp

data Action =
    GetProfile GetProfileReq (Maybe TwoFactor)
  | StateActionUpdate State

update :: forall eff. Runner eff eff -> Action -> State -> EffModel State Action (AuthEffects eff)
update runner action state =
  case action of
    GetProfile req mtf ->
      onlyEffects state $ pure $ do
        r <- runReaderT runner $ getProfile state
        pure $ case r of
          Left tfr ->
            StateActionUpdate $ StateNeedsTwoFactor tfr
          Right (Left e) ->
            StateActionUpdate $ StateError e
          Right (Right r) ->
            StateActionUpdate $ StateProfile $ getAPIResponseData $ r
    StateActionUpdate state ->
      noEffects state
```

Does that help?

**Comment by PipocaQuemada** [comment]
I'm not sure what your runner function would look like, there - the runner is what takes the TwoFactorRequired and prompts for the two factor code.  The main reason for this is that the api uses HMAC for authentication so login performs ECDH to generate a key for HMAC, and the server expects login not to change the public key it provides when retrying login with a two factor code.  This means that the api library needs to repeatedly prompt the user for a two factor code before it returns, since we don't really want to return the 

What I currently have (which works) is something like:

    authChan :: Channel Action
    authChan = runChan $ channel NoOp
    authSignal = subscribe authChan

    affjaxRunner :: forall a. Runner a
    affjaxRunner call = runAffjax Nothing
      where
        runAffjax twoFactor =
          do resp <- lift $ call twoFactor 
             case resp of
               Left TwoFARequired -> do
                 twoFAToken <- lift $ do twoFATokenVar <- makeVar
                                         forkAff $ liftEff $ send authChan (PromptTwoFactor twoFATokenVar)
                                         --block until the TwoFA component passes back the two factor token
                                         twoFAToken <- takeVar twoFATokenVar
                                         pure twoFAToken
                 runAffjax $ Just twoFAToken
               Right success -> liftEff $ send authChan AuthDone >>= \_ -> pure success

    data Action
      = TwoFAAct (TwoFA.Action) 
      | LoginAct (Login.Action) 
      | ProfileAct (Profile.Action)
      | PageView R.Route 
      | PromptTwoFactor (AVar String)
      | AuthDone

    type State =
      { route :: R.Route
      , authReq :: Maybe AuthenticationRequired -- used in view to pop up the two factor modal
      , login :: Login.State
      , twoFA :: TwoFA.State
      , profile :: Profile.State
      }

    init :: State
    init =
      { route: R.Home
      , login: Login.init affjaxRunner
      , profile: Profile.init affjaxRunner
      , twoFA: TwoFA.init
      , authReq: Nothing
      }


    -- in Main:
    config state = do
      urlSignal <- sampleUrl
      let routeSignal = urlSignal ~> \r -> PageView (match r)
      pure
        { initialState: state
        , update: update
        , view: view
        , inputs: [ authSignal 
                  , routeSignal
                  ]
        }

    -- helper functions for running requests:     
    run call runner = runMaybeT $ runReaderT call runner
    extractResult :: forall a b. (a -> b) -> b -> Maybe (AffjaxResponse (APIResponse a)) -> b
    extractResult f _ (Just {status: StatusCode 200, response: S response}) = f response
    extractResult _ default _ = default

    -- in Profile:
    update GetProfile state =  onlyEffects state [ (extractResult SetProfile NoOp <$> run (getProfile req) state.runner)]

Is there a better way to do this, that doesn't require the authSignal?

**Comment by alexmingoia** [comment]
I'm archiving most of the discussion threads. If you'd like to continue the discussion I'd prefer if you posted a question on StackOverflow or [Gitter](https://gitter.im/alexmingoia/purescript-pux). Thanks.
