### ISSUE TITLE
SVG "text" element

### ISSUE THREAD

**Issue by wereHamster** [alexmingoia/purescript-pux#88]
The `<text>` element is missing form `Pux.Html.Elements`. Probably because the function would be in name conflict with the existing `text` function (`text :: forall a. String -> Html a`).

In my project I created a `svgText` function, but I'm not happy with the naming because it is not consistent with the other functions.

What about removing the current `text` function in favour of `fromString` (which it really is, after all), and so we can use `text` for the HTML element?

**Comment by charleso** [comment]
I'm not strongly against this, but this would definitely cause some churn in our production pux code, and I suspect other peoples too.

Would it make sense to have a separate `Pux.Svg.Elements` module which may (or may not) have a similar `text` function?

**Comment by alexmingoia** [comment]
Pux 8 has moved to using purescript-smolder for markup. It's currently lacking svg constructors, but that should be pretty easy to add. The move to purescript-smolder was done to make things more modular and allow for a monoidal markup data structure. See bodil/purescript-smolder#19

**Comment by wereHamster** [comment]
I looked at smolder and it seems to have an API to easily create custom tags (`svgText = parent "text"`). That should be sufficient for my use case.
