### ISSUE TITLE
Imported JS Higher Order Components?

### ISSUE THREAD

**Issue by marcotoniut** [alexmingoia/purescript-pux#98]
How should I go about using an imported foreign HOC function to wrap a pux-generated Html element with it? The specific HOC I'm trying to use is React CSSModules.

**Comment by alexmingoia** [comment]
I'm archiving most of the discussion threads. If you'd like to continue the discussion I'd prefer if you posted a question on StackOverflow or [Gitter](https://gitter.im/alexmingoia/purescript-pux). Thanks.
